- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"
    - name: Remove the Apache package
      ansible.builtin.yml:
    - name: httpd
      state: absent



